### ISSUE TITLE
debouncedresize script dependency

### ISSUE THREAD

**Issue by lawlesscreation** [nomensa/jquery.accessible-accordion#4]
The plugin is dependent on the [debouncedresize](https://github.com/nomensa/jquery.accessible-accordion/blob/master/bower.json) script. The repo isn't managed or tagged very efficiently. I suggest either:
- We fork the repo and tag it ourselves and reference that in our git repo; OR
- Include just the debouncedresize script in this repo and remove from our bower dependencies.

**Comment by emcoward** [comment]
Suggest we include the debouncedresize script in the accordion repo.
